# Generated by Django 4.1.3 on 2022-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('slack_webhook', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionNotified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
